name: VendEra CI

on:
  push:
    branches:
      - main

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
         sudo apt-get update
         sudo apt-get install -y maven

      - name: Build Eureka Server
        working-directory: ./VendEra-Backend/Eureka-Server
        run: mvn clean package -DskipTests

      - name: Build Product Service
        working-directory: ./VendEra-Backend/Product-Service
        run: mvn clean package -DskipTests

      - name: Build Auth Service
        working-directory: ./VendEra-Backend/Auth-Service
        run: mvn clean package -DskipTests
