name: VendEra CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # 1. Checkout
      # =========================

      - name: Checkout code
        uses: actions/checkout@v4


      # =========================
      # 2. AWS Authentication
      # =========================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::121316354144:role/Vendera-GitHubActions-ECR
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com


      # =========================
      # 3. Java + Maven
      # =========================

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven


      # =========================
      # 4. Build ALL JARs
      # =========================

      - name: Build Eureka Server
        working-directory: ./VendEra-Backend/Eureka-Server
        run: mvn clean package -DskipTests

      - name: Build Product Service
        working-directory: ./VendEra-Backend/Product-Service
        run: mvn clean package -DskipTests

      - name: Build Auth Service
        working-directory: ./VendEra-Backend/Auth-Service
        run: mvn clean package -DskipTests

      - name: Build Order Service
        working-directory: ./VendEra-Backend/Order-Service
        run: mvn clean package -DskipTests

      - name: Build Payment Service
        working-directory: ./VendEra-Backend/Payment-Service
        run: mvn clean package -DskipTests

      - name: Build API Gateway
        working-directory: ./VendEra-Backend/Api-Gateway
        run: mvn clean package -DskipTests


      # =========================
      # 5. Build ALL Docker Images
      # =========================

      - name: Build Eureka Docker Image
        working-directory: ./VendEra-Backend/Eureka-Server
        run: docker build -t vendera-eureka:ci .

      - name: Build Product Docker Image
        working-directory: ./VendEra-Backend/Product-Service
        run: docker build -t vendera-product:ci .

      - name: Build Auth Docker Image
        working-directory: ./VendEra-Backend/Auth-Service
        run: docker build -t vendera-auth:ci .

      - name: Build Order Docker Image
        working-directory: ./VendEra-Backend/Order-Service
        run: docker build -t vendera-order:ci .

      - name: Build Payment Docker Image
        working-directory: ./VendEra-Backend/Payment-Service
        run: docker build -t vendera-payment:ci .

      - name: Build API Gateway Docker Image
        working-directory: ./VendEra-Backend/Api-Gateway
        run: docker build -t vendera-api-gateway:ci .


      # =========================
      # 6. Tag + Push Eureka
      # =========================

      - name: Tag Eureka Image
        run: |
          docker tag vendera-eureka:ci \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-eureka:latest

      - name: Push Eureka Image
        run: |
          docker push \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-eureka:latest


      # =========================
      # 7. Tag + Push Product
      # =========================

      - name: Tag Product Image
        run: |
          docker tag vendera-product:ci \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-product:latest

      - name: Push Product Image
        run: |
          docker push \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-product:latest


      # =========================
      # 8. Tag + Push Auth
      # =========================

      - name: Tag Auth Image
        run: |
          docker tag vendera-auth:ci \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-auth:latest

      - name: Push Auth Image
        run: |
          docker push \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-auth:latest


      # =========================
      # 9. Tag + Push Order
      # =========================

      - name: Tag Order Image
        run: |
          docker tag vendera-order:ci \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-order:latest

      - name: Push Order Image
        run: |
          docker push \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-order:latest


      # =========================
      # 10. Tag + Push Payment
      # =========================

      - name: Tag Payment Image
        run: |
          docker tag vendera-payment:ci \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-payment:latest

      - name: Push Payment Image
        run: |
          docker push \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-payment:latest


      # =========================
      # 11. Tag + Push API Gateway
      # =========================

      - name: Tag API Gateway Image
        run: |
          docker tag vendera-api-gateway:ci \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-api-gateway:latest

      - name: Push API Gateway Image
        run: |
          docker push \
          121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-api-gateway:latest


      # =========================
      # 12. Deploy ALL Services
      # ==========================

      - name: Deploy All Services to EC2
        run: |
          aws ssm send-command \
            --region ap-south-1 \
            --document-name "AWS-RunShellScript" \
            --instance-ids "i-004b11983589d3e6b" \
            --parameters 'commands=[

              "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 121316354144.dkr.ecr.ap-south-1.amazonaws.com",

              "docker pull 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-eureka:latest",
              "docker pull 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-product:latest",
              "docker pull 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-auth:latest",
              "docker pull 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-order:latest",
              "docker pull 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-payment:latest",
              "docker pull 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-api-gateway:latest",

              "docker stop vendera-eureka-ecr || true",
              "docker rm vendera-eureka-ecr || true",
              "docker stop vendera-eureka || true",
              "docker rm vendera-eureka || true",

              "docker stop vendera-product || true",
              "docker rm vendera-product || true",

              "docker stop vendera-auth || true",
              "docker rm vendera-auth || true",

              "docker stop vendera-order || true",
              "docker rm vendera-order || true",

              "docker stop vendera-payment || true",
              "docker rm vendera-payment || true",

              "docker stop vendera-api-gateway || true",
              "docker rm vendera-api-gateway || true",

              "docker run -d --name vendera-eureka --network vendera-net -p 8761:8761 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-eureka:latest",

              "docker run -d --name vendera-product --network vendera-net --env-file /home/ec2-user/Vendera/Product/product.env -p 8762:8762 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-product:latest",

              "docker run -d --name vendera-auth --network vendera-net --env-file /home/ec2-user/Vendera/Auth/auth.env -p 8766:8766 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-auth:latest",

              "docker run -d --name vendera-order --network vendera-net --env-file /home/ec2-user/Vendera/Order/order.env -p 8763:8763 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-order:latest",

              "docker run -d --name vendera-payment --network vendera-net --env-file /home/ec2-user/Vendera/Payment/payment.env -p 8764:8764 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-payment:latest",

              "docker run -d --name vendera-api-gateway --network vendera-net --env-file /home/ec2-user/Vendera/Api-Gateway/gateway.env -p 8080:8080 121316354144.dkr.ecr.ap-south-1.amazonaws.com/vendera-api-gateway:latest"

            ]'