name: VendEra CI

on:
  push:
    branches:
      - main

permissions: 
  id-token: write
  contents: read

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::121316354144:role/Vendera-GitHubActions-ECR
          aws-region: ap-south-1

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
         sudo apt-get update
         sudo apt-get install -y maven

      - name: Build Eureka Server
        working-directory: ./VendEra-Backend/Eureka-Server
        run: mvn clean package -DskipTests

      - name: Build Product Service
        working-directory: ./VendEra-Backend/Product-Service
        run: mvn clean package -DskipTests

      - name: Build Auth Service
        working-directory: ./VendEra-Backend/Auth-Service
        run: mvn clean package -DskipTests
      
      - name: Build Order Service
        working-directory: ./VendEra-Backend/Order-Service
        run: mvn clean package -DskipTests

      - name: Build Payment Service
        working-directory: ./VendEra-Backend/Payment-Service
        run: mvn clean package -DskipTests

      - name: Build API Gateway
        working-directory: ./VendEra-Backend/Api-Gateway
        run: mvn clean package -DskipTests
      
      - name: Build Eureka Docker Image
        working-directory: ./VendEra-Backend/Eureka-Server
        run: docker build -t vendera-eureka:ci .

      - name: Build Product Docker Image
        working-directory: ./VendEra-Backend/Product-Service
        run: docker build -t vendera-product:ci .

      - name: Build Auth Docker Image
        working-directory: ./VendEra-Backend/Auth-Service
        run: docker build -t vendera-auth:ci .

      - name: Build Order Docker Image
        working-directory: ./VendEra-Backend/Order-Service
        run: docker build -t vendera-order:ci .

      - name: Build Payment Docker Image
        working-directory: ./VendEra-Backend/Payment-Service
        run: docker build -t vendera-payment:ci .

      - name: Build API Gateway Docker Image
        working-directory: ./VendEra-Backend/Api-Gateway
        run: docker build -t vendera-api-gateway:ci .

